[package]
name = "count"
description = "Count lines of code in a project"
version = "0.1.0"
edition = "2024"
authors = ["Juan Milkah <juanmilkah@gmail.com"]
repository = "https://github.com/juanmilkah/count"
license = "MIT"

[dependencies]
anyhow = "1.0.97"
